### ISSUE TITLE
Code review Alfie Holman 25798788

### ISSUE THREAD

**Issue by alfieH0** [JonnyRichardss/CMP1903M-A01-2223-Jonathan-Richards#1]
overall the program is very efficient and works well with very minimal code required 
however, I think you should edit the testing class so its a menu that will allow you to more easily chose between shuffling styles and also allow the user to more easily chose how many cards it should deal with instead of having to edit the code to test these features but overall a very good program

**Comment by JonnyRichardss** [comment]
Thanks for the review, I have added the menu feature as per your suggestion.
