### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by mitm17** [JonnyRichardss/CMP1903M-A01-2223-Jonathan-Richards#2]
Method arguments: The shuffleCardPack method takes an integer argument typeOfShuffle to determine the type of shuffle. It would be clearer if this argument was an enum instead of an integer, as it would make the code more readable and less prone to errors.
It would be better to use an enumeration for Suit instead of an integer.
I haven't got anything else to comment on as its looking good!

**Comment by JonnyRichardss** [comment]
Thanks for the review, I have added the suggested enums with some integer casting options for convenience.
